### ISSUE TITLE
triangular solvers outputting zero vector?

### ISSUE THREAD

**Issue by gadamico** [uwhpsc-2016/homework2#31]
This is just a shameless appeal for help.  Well, okay, maybe there is a little shame.

My triangular solvers seem to be outputting zeros no matter what the input is!  My mat_mat code has failed a few tests as well....  But in all three cases I've stared at the code and it really seems correct to me.  Argh.

Grateful for any help you can offer; perhaps you could, for example, confirm or deny that my triangular solvers will (somehow) fill 'out' with zeros?  When I tried A = [1 0 0 0; 1 1 0 0; 1 1 1 0; 1 1 1 1] and b = [1; 2; 3; 4], where 'out' should be [1; 1; 1; 1], I got [0; 0; 0; 0].

You should find my most recent work in my private repository.

**Comment by cswiercz** [comment]
Closing since this issue concerns a student's own code.
