### ISSUE TITLE
Linking math.h in SMC terminal

### ISSUE THREAD

**Issue by natwall27** [uwhpsc-2016/homework2#39]
I have just switched from doing my work in Code:Blocks to SMC. I have been unsucessful at linking math.h to file. 

I have tried: 

$ gcc homework2.c -o homework 2 -lm
and
$gcc -lm

Does anyone have other suggestions on how to link math.h?

Thank you!

**Comment by mvelegar** [comment]
I see a number of issues in your command. 
(1) Do you have a homework2.c file? The repo has been set up such that you only had `lin_alg.c` and `solvers.c` under src
(2) There should be no space here `homework 2`
(3) Please paste the exact error you see on SMC

**Comment by natwall27** [comment]
Thank you for your help! I apologize about the code in my repo, it is not up-to-date. It was just a first draft. I just committed my most recent code.
