### ISSUE TITLE
folders missing from repo. Dont have a report folder

### ISSUE THREAD

**Issue by avs2805** [uwhpsc-2016/homework2#53]
<img width="747" alt="untitled" src="https://cloud.githubusercontent.com/assets/15151703/15088537/7ac1807a-13aa-11e6-9f8b-b192f9fd9f06.png">

**Comment by cswiercz** [comment]
This was addressed last week. Please see here: https://github.com/uwhpsc-2016/homework2/issues/15

**Comment by avs2805** [comment]
@cswiercz Thanks! I had not pushed it to the master.
