### ISSUE TITLE
grading of homework 2

### ISSUE THREAD

**Issue by swcarmer** [uwhpsc-2016/homework2#54]
Was this already done? Since it wasn't mentioned at the beginning of the class, I thought perhaps it had been posted already but my Canvas login doesn't show any homework 2 grading. Thanks.

**Comment by yusufmansour** [comment]
Same here. No grades in canvas yet for hw2.

**Comment by mvelegar** [comment]
Grades will be up no later than tomorrow night for Homework 2.

**Comment by swcarmer** [comment]
okay, thanks!
