### ISSUE TITLE
Homework 2 How to obtain?

### ISSUE THREAD

**Issue by nishalad95** [uwhpsc-2016/homework2#9]
Hi There,

Are we supposed to receive an email link to accept the invitation for homework2, because I didn't receive a link. Otherwise, I understand that we can clone homework 2 to our local repository, but when we push it up to github will it change the homework2 folder that is there for everyone in stead of just changing my private repo? I'm not sure how we can set up homework2 in the same way as homework1.

ThanksHi There,

Are we supposed to receive an email link to accept the invitation for homework2, because I didn't receive a link. Otherwise, I understand that we can clone homework 2 to our local repository, but when we push it up to github will it change the homework2 folder that is there for everyone in stead of just changing my private repo? I'm not sure how we can set up homework2 in the same way as homework1.

Thanks

**Comment by jhyearsley** [comment]
You should receive an email link. Maybe recheck email; for me the message was from 'UW Canvas' with subject line 'Homework #2 Available: AMATH 483 A: High-Performance Scientific Computing'.

**Comment by nishalad95** [comment]
Thank you! I'll check again
